apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: load-balancer
resources:
  - namespace.yaml
  - configmap.yaml
  - localstack.yaml
  - osb.yaml
  - worker.yaml
  - sovereign.yaml
  - envoy-fleet.yaml
  - backends.yaml
  - sidecars.yaml
