apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: load-balancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.4
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: dynamodb,sqs,s3,route53,cloudfront
            - name: DEFAULT_REGION
              value: us-east-1
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: load-balancer
spec:
  selector:
    app: localstack
  ports:
    - port: 4566
      targetPort: 4566
